from __future__ import annotations

import html
import json
import re
import sys
import unicodedata
from pathlib import Path

from .config import (BUNDESLAENDER, COUNTRY_AREAS, COUNTRY_PAGES,
                     COUNTRY_SLUGS, FRANCE_REGIONS, PAGES_BASE_PATH,
                     SITE_BASE_URL)
from .export import write_text_atomic
from .pages_l10n import (AMENITY, BOARD_LABEL, FRANCE_REGION_FORMS, L,
                         board_file)

# One static page per swept area, regenerated by every full build.
#
# Why they exist: the map is a single URL for eleven countries, so search
# demand shaped like "Wickeltisch Bayern" — or "puslebord Danmark", or "table
# à langer Bretagne" — has nothing to match: the place names live inside a
# multi-megabyte geojson that crawlers read as a download, not as text. These
# pages put the counts and the names into HTML.
#
# Each page is written in the language its readers search in: German for the
# 16 Bundesländer (and Austria and Switzerland), Danish for Denmark, French
# for France and its 13 régions, and so on — the routing lives in
# config.COUNTRY_PAGES, the strings in pages_l10n.py. That is also why they
# carry no hreflang alternates: each page exists in exactly one language,
# same reasoning as impressum.html and datenschutz.html.
#
# Unlike index.html, these files are rewritten nightly, so hard-coded counts
# in the copy, the meta description and the JSON-LD are safe here — the "no
# counts in the markup" rule on the homepage is about hand-maintained files
# that rot.

GERMAN_MONTHS = L["de"]["months"]

# ä→ae rather than ä→a: "baden-wuerttemberg" is the spelling German readers and
# German keyboards produce, and the slug is a public URL we have to keep stable.
# Everything else non-ASCII is folded to its base letter (Île→ile, Česko→cesko)
# — the German table runs first, so the 16 existing slugs cannot change.
_TRANSLIT = str.maketrans({
    "ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss",
    "Ä": "Ae", "Ö": "Oe", "Ü": "Ue",
})

# The amenity tag is a controlled OSM vocabulary, so a lookup table can cover
# it — one per page language in pages_l10n.py; this is the German one, kept
# under its old name. Anything else falls back to the raw value with
# underscores stripped — a page that reads half-translated is better than one
# that silently drops the type. `null` (a shop, most often a dm or Rossmann)
# has no amenity at all and renders as an em dash.
AMENITY_DE = AMENITY["de"]

# The pages sit one directory below the site root (PAGES_BASE_PATH), so this
# reaches the map, the methods page and the legal pages. Relative on purpose:
# only the canonical and the JSON-LD breadcrumb have to be absolute, and
# relative links mean a page renders and navigates correctly off a local
# `python3 -m http.server -d web` too.
UP = "../"

STATUS_ORDER = ("accessible", "female_only", "unknown")
STATUS_DE = L["de"]["statuses"]
STATUS_CLASS = {"accessible": "g", "female_only": "r", "unknown": "u"}


def slugify(name: str) -> str:
    """URL slug for an area page. The names are fixed lists, so this only has
    to be correct for them — but it is a function rather than a hand-written
    table so a name and its slug cannot drift apart (test_pages pins all of
    them). German umlauts become ae/oe/ue (the phone-book spelling readers
    type); every other accent folds to its base letter, so Île-de-France and
    Česko produce typable ASCII slugs too."""
    override = COUNTRY_SLUGS.get(name)
    if override:
        # Non-Latin-script names (Ελλάδα, Україна …) would fold to nothing
        # here; their slug is the romanization their readers actually type,
        # declared next to the name in config.
        return override
    s = name.translate(_TRANSLIT).lower()
    s = unicodedata.normalize("NFKD", s)
    s = "".join(c for c in s if not unicodedata.combining(c))
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-")


def sort_key(name: str) -> tuple:
    """Alphabetical order a German reader expects: Ärztehaus next to Apotheke,
    not stranded after Zoo where a raw codepoint sort puts it.

    ä sorts as a here, not as ae — that is DIN 5007-1, the ordering used for
    lists of names, and deliberately NOT the ae the slugs use (those follow the
    phone-book spelling because they are URLs someone might type). Decomposing
    and dropping the combining marks generalises it to the é and å that OSM
    names in a German Land do contain."""
    folded = unicodedata.normalize("NFKD", name.replace("ß", "ss").casefold())
    stripped = "".join(c for c in folded if not unicodedata.combining(c))
    return (stripped, name)


def fmt_num(n, lang: str = "de") -> str:
    """1234567 → '1.234.567' (de) / '1,234,567' (en) / '1 234 567' with a
    no-break space for the languages that group digits with a space."""
    return f"{int(n):,}".replace(",", L[lang]["num_sep"])


def de_num(n) -> str:
    """The German pages' formatter, kept under its old name — the leaderboard
    imports it too."""
    return fmt_num(n, "de")


def fmt_date(iso: str, lang: str = "de") -> str:
    """'2026-08-04T21:10:40+00:00' → '4. August 2026' / '4 August 2026' / …
    Hand-rolled because strftime('%B') follows the process locale, which on
    the server is C — and because Czech and Polish dates need the genitive
    month, which no locale-free stdlib call produces."""
    try:
        y, m, d = int(iso[0:4]), int(iso[5:7]), int(iso[8:10])
        return L[lang]["date_fmt"].format(d=d, m=L[lang]["months"][m - 1], y=y)
    except (ValueError, IndexError, TypeError):
        return ""


def de_date(iso: str) -> str:
    return fmt_date(iso, "de")


def amenity_label(amenity, lang: str = "de") -> str:
    if not amenity:
        return "—"
    return AMENITY[lang].get(amenity, str(amenity).replace("_", " "))


def group_by_area(features, area_by_key) -> dict:
    """Split the deduped feature list by the sweep area each object came from.

    `area_by_key` is {(osm_type, osm_id): area_name}, recorded while sweeping —
    the geojson itself carries no region field, and the Overpass area query is
    the only authority on which Land an object sits in. An object on a Länder
    boundary is returned by two sweeps and lands in the first one, matching how
    dedup_elements() keeps the first copy for the map."""
    out: dict[str, list] = {}
    for f in features:
        p = f["properties"]
        area = area_by_key.get((p["osm_type"], p["osm_id"]))
        if area is not None:
            out.setdefault(area, []).append(f)
    return out


def _bbox(features, name: str = "") -> list | None:
    """Feature bbox, padded, for the map deep link. Data-driven rather than a
    hard-coded box: the features come out of that area's own Overpass query, so
    their extent is inside it by construction and never needs maintaining. The
    minimum span keeps an area with a single place from producing a zero-width
    box that fitBounds turns into a maximum-zoom view of one pin.

    Plain min/max, so an area straddling the antimeridian would produce a
    box the wrong way round the planet. New Zealand's relation does (the
    Chatham Islands sit at 176°W); as of 2026-09-04 no changing_table is
    mapped there. The day one appears, the page drops its map link rather
    than shipping a box the wrong way round the planet — a missing CTA is
    visible, a whole-world view behind a "New Zealand" button is not. The
    real fix then is to wrap the negative longitudes by +360 here and let
    parseBbox accept an east past 180. The drop is announced as a WARN line
    so it shows up in pipeline.log and on the ops page, and does not go
    unnoticed for the months a missing button can pass for a design choice."""
    if not features:
        return None
    lons = [f["geometry"]["coordinates"][0] for f in features]
    lats = [f["geometry"]["coordinates"][1] for f in features]
    min_lon, max_lon, min_lat, max_lat = min(lons), max(lons), min(lats), max(lats)
    if max_lon - min_lon > 180:
        print(f"  WARN {name or 'area'}: features span the antimeridian "
              f"(lon {min_lon:.2f}..{max_lon:.2f}), page ships without a map "
              "link — wrap the west longitudes by +360 in _bbox()",
              file=sys.stderr)
        return None
    pad_lon = max((max_lon - min_lon) * 0.04, 0.05)
    pad_lat = max((max_lat - min_lat) * 0.04, 0.03)
    return [round(min_lon - pad_lon, 4), round(min_lat - pad_lat, 4),
            round(max_lon + pad_lon, 4), round(max_lat + pad_lat, 4)]


def summarize(name: str, features, toilets_total: int) -> dict:
    """Everything one area page needs, computed from that area's features.

    Named places are grouped by name: the dataset holds 181 shops called "dm"
    and 62 McDonald's, and 181 identical rows would read as generated filler
    rather than as data. The count carries the same information in one row."""
    status_counts = {s: 0 for s in STATUS_ORDER}
    groups: dict[str, dict] = {}
    unnamed = 0
    for f in features:
        p = f["properties"]
        status = p.get("status")
        if status in status_counts:
            status_counts[status] += 1
        place = (p.get("name") or "").strip()
        if not place:
            unnamed += 1
            continue
        g = groups.setdefault(place, {"name": place, "count": 0, "amenities": {},
                                      "statuses": {s: 0 for s in STATUS_ORDER}})
        g["count"] += 1
        if status in g["statuses"]:
            g["statuses"][status] += 1
        a = p.get("amenity")
        g["amenities"][a] = g["amenities"].get(a, 0) + 1
    named = []
    for g in sorted(groups.values(), key=lambda g: sort_key(g["name"])):
        # A chain can carry different amenity values across branches (café vs
        # fast_food); the most common one describes the group honestly enough,
        # and ties break on the value so the page is byte-stable between runs.
        top = sorted(g["amenities"].items(), key=lambda kv: (-kv[1], str(kv[0])))[0][0]
        named.append({"name": g["name"], "count": g["count"],
                      "amenity": top, "statuses": g["statuses"]})
    return {
        "name": name,
        "slug": slugify(name),
        "tables": len(features),
        "accessible": status_counts["accessible"],
        "female_only": status_counts["female_only"],
        "unknown": status_counts["unknown"],
        "toilets_total": toilets_total,
        "named": named,
        "named_places": len(features) - unnamed,
        "unnamed": unnamed,
        "bbox": _bbox(features, name),
    }


# ---- Rendering -------------------------------------------------------------
# Place names, amenity values and every other interpolated string originate in
# OpenStreetMap, which anyone can edit — so every one of them goes through
# esc(). The surrounding markup is a constant in this file or pages_l10n.py.

def esc(s) -> str:
    return html.escape(str(s), quote=True)


def _jsonld(obj) -> str:
    """A <script> block's content is raw text, so HTML-escaping is exactly the
    wrong tool there (&quot; would land literally and break the JSON). json
    encodes it; escaping "</" is what stops any value from closing the tag."""
    body = json.dumps(obj, ensure_ascii=False).replace("</", "<\\/")
    return f'<script type="application/ld+json">{body}</script>\n\n'


# The same mark index.html carries, inlined for the same reason: a data URI
# costs no request and — unlike a root-relative /icon.svg — resolves from any
# directory depth, so the pages under wickeltische/ need no {up} dance. Without
# it a browser falls back to /favicon.ico, which this site does not serve: every
# generated page logged a 404 until 2026-08-17.
ICON = (
    '<link rel="icon" href="data:image/svg+xml,'
    "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E"
    "%3Ccircle cx='12' cy='12' r='11' fill='%23009e73'/%3E"
    "%3Crect x='5' y='12' width='14' height='2.6' rx='1.3' fill='%23fff'/%3E"
    "%3Ccircle cx='9' cy='9' r='2.2' fill='%23fff'/%3E"
    "%3Crect x='11.5' y='7.8' width='6.5' height='2.4' rx='1.2' fill='%23fff'/%3E"
    '%3C/svg%3E">'
)

STYLE = """\
  :root {
    --bg: #ffffff; --fg: #1c1c1c; --muted: #5a5a5a; --line: #d8d8d8;
    --green: #1a7f37; --red: #c0392b; --grey: #6e6e6e; --accent: #0b5fa5;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #1b1b1d; --fg: #e8e8e8; --muted: #a5a5a5; --line: #3a3a3d;
      --green: #4cc26b; --red: #e06553; --grey: #9a9a9a; --accent: #6ab0e8;
    }
  }
  body {
    margin: 0 auto; max-width: 46rem; padding: 1.5rem 1rem 4rem;
    background: var(--bg); color: var(--fg);
    font: 16px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif;
  }
  h1 { font-size: 1.6rem; margin: 0.5rem 0 0; }
  h2 { font-size: 1.2rem; margin-top: 2.2rem; border-bottom: 1px solid var(--line); padding-bottom: 0.3rem; }
  a { color: var(--accent); }
  .muted { color: var(--muted); font-size: 0.9rem; }
  .back { font-size: 0.9rem; }
  .dot { display: inline-block; width: 0.7em; height: 0.7em; border-radius: 50%;
         margin-right: 0.3em; vertical-align: baseline; }
  .g { background: var(--green); } .r { background: var(--red); } .u { background: var(--grey); }
  .cta { display: inline-block; margin: 0.6rem 0; padding: 0.55rem 0.9rem;
         border: 1px solid var(--accent); border-radius: 6px; text-decoration: none; }
  /* Long lists on a phone: let the table scroll sideways instead of the page. */
  .scroll { overflow-x: auto; }
  table { border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem; width: 100%; }
  th, td { border: 1px solid var(--line); padding: 0.3rem 0.55rem; text-align: right;
           white-space: nowrap; }
  th:first-child, td:first-child, th.l, td.l { text-align: left; white-space: normal; }
  th { font-weight: 600; }
  td.zero { color: var(--muted); }
  ul.laender { columns: 2; list-style: none; padding: 0; font-size: 0.95rem; }
  ul.laender li { margin: 0.25rem 0; break-inside: avoid; }
"""

# The German footer, kept under its old name — the leaderboard's German page
# imports it.
FOOTER = L["de"]["footer"]


# The social card. Until 2026-08-25 the generated pages carried no og:* at
# all, so Mastodon and Discourse fell back to <title> + description and
# rendered a text-only card — which is why a post to a non-German audience is
# better off linking the country page than the apex, whose og:* block is
# German whatever the ?lang= (see index.html). Here the title and description
# are already the page's own language, so the card only needed a picture.
#
# The screenshot has the app's chrome baked into it, so there is one per
# language we have a render for and English for the rest: an English picture
# under a Danish page reads better than a German one. Cloudflare holds the
# image for four hours and the scrapers cache the card far longer, so a new
# picture ships under a new ?v= or the edge keeps serving the old one.
OG_IMAGE = {"de": "og-image.jpg"}
OG_IMAGE_FALLBACK = "og-image-en.jpg"
OG_IMAGE_VERSION = "eu44"
OG_IMAGE_SIZE = (1200, 630)


def _og(title: str, description: str, canonical: str, lang: str,
        base_url: str) -> str:
    image = f"{base_url}/{OG_IMAGE.get(lang, OG_IMAGE_FALLBACK)}"
    w, h = OG_IMAGE_SIZE
    return f"""<meta property="og:type" content="website">
<meta property="og:site_name" content="PapaMap">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="{esc(canonical)}">
<meta property="og:image" content="{esc(image)}?v={OG_IMAGE_VERSION}">
<meta property="og:image:width" content="{w}">
<meta property="og:image:height" content="{h}">
<meta name="twitter:card" content="summary_large_image">"""


def _head(title: str, description: str, canonical: str, lang: str = "de",
          base_url: str = SITE_BASE_URL) -> str:
    return f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="{esc(canonical)}">
{_og(title, description, canonical, lang, base_url)}
{ICON}
<style>
{STYLE}</style>
</head>
<body>
"""


def _status_cells(counts, lang: str = "de") -> str:
    """The three status columns. A zero renders as a muted dash: in a 300-row
    table a column of "0"s is noise that hides the numbers that aren't zero."""
    out = []
    for s in STATUS_ORDER:
        n = counts.get(s, 0)
        out.append('<td class="zero">–</td>' if not n
                   else f"<td>{fmt_num(n, lang)}</td>")
    return "".join(out)


def _status_head(labels=STATUS_DE) -> str:
    return "".join(
        f'<th><span class="dot {STATUS_CLASS[s]}"></span>{esc(labels[s])}</th>'
        for s in STATUS_ORDER)


def _map_link(bbox, label: str) -> str:
    """Deep link into the map at this area's extent. Without a bbox the map
    would open on the whole-Europe home view, which is no answer to "where in
    Hessen" — app.js reads the param and fits those bounds."""
    if not bbox:
        return ""
    q = ",".join(str(v) for v in bbox)
    return f'<p><a class="cta" href="{UP}?bbox={esc(q)}">{esc(label)} &rarr;</a></p>\n'


def _nav_list(items, lang: str, exclude_href: str = "") -> str:
    """The two-column link list the pages navigate each other with — sibling
    Länder/régions on one page, the country pages on all of them. Counts are
    formatted in the page's language; the labels are endonyms and need none."""
    lis = "".join(
        f'<li><a href="{esc(it["href"])}">{esc(it["label"])}</a> '
        f'<span class="muted">{fmt_num(it["tables"], lang)} '
        f'{esc(L[lang]["places_unit"])}</span></li>'
        for it in items if it["href"] != exclude_href)
    return f'<ul class="laender">{lis}</ul>\n' if lis else ""


def _countries_section(countries, lang: str, own_href: str) -> str:
    if not countries:
        return ""
    body = _nav_list(countries, lang, exclude_href=own_href)
    if not body:
        return ""
    return f'<h2>{esc(L[lang]["countries_h2"])}</h2>\n' + body


def render_area(page: dict, generated_at: str, base_url: str = SITE_BASE_URL,
                base_path: str = PAGES_BASE_PATH) -> str:
    """One area page — a Bundesland, a whole country or a French région — in
    the language page["lang"] names. The page dict carries what differs
    between kinds: the name forms (see config.COUNTRY_PAGES for why there are
    three of them), the breadcrumb parent, the back links, the sibling areas
    and the shared country list. Everything language-shaped comes from
    pages_l10n.L."""
    lang = page["lang"]
    t = L[lang]
    summary = page["summary"]
    name, slug = summary["name"], summary["slug"]
    name_in = page.get("name_in") or f"in {name}"
    name_for = page.get("name_for") or name
    name_in_cap = name_in[0].upper() + name_in[1:]
    tables, unknown = summary["tables"], summary["unknown"]
    pct = round(100 * unknown / tables) if tables else 0
    date = fmt_date(generated_at, lang)
    canonical = f"{base_url}{base_path}{slug}.html"
    kw = {
        "name": esc(name), "name_in": esc(name_in), "name_for": esc(name_for),
        "In": esc(name_in_cap), "pct": pct, "up": UP, "methods": t["methods"],
        "tables": fmt_num(tables, lang),
        "accessible": fmt_num(summary["accessible"], lang),
        "female_only": fmt_num(summary["female_only"], lang),
        "unknown": fmt_num(unknown, lang),
        "toilets": fmt_num(summary["toilets_total"], lang),
        "named": fmt_num(len(summary["named"]), lang),
        "named_places": fmt_num(summary["named_places"], lang),
        "unnamed": fmt_num(summary["unnamed"], lang),
    }
    # Title and description pass through _head's own esc(), so they get the
    # raw name forms rather than pre-escaped ones.
    raw = {**kw, "name": name, "name_in": name_in, "name_for": name_for}
    title = t["title"].format(**raw)
    desc = t["meta_desc"].format(**raw)

    parts = [_head(title, desc, canonical, lang, base_url)]
    # Breadcrumbs are the one bit of structured data that earns its place here:
    # they tell Google these are the leaves of one section, not loose pages.
    crumbs = [("PapaMap", f"{base_url}/")] + page.get("crumb_extra", [])
    parts.append(_jsonld({
        "@context": "https://schema.org", "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": n, "item": u}
            for i, (n, u) in enumerate(crumbs + [(name, canonical)])
        ],
    }))
    # Every generated page carries its language's leaderboard in the back row:
    # before 2026-08-23 only the German index linked it, so 30 languages had
    # no path from their pages to their own leaderboard.
    back_links = list(page["back"]) + [(BOARD_LABEL[lang], board_file(lang))]
    back = " · ".join(
        f'<a href="{esc(href)}">{"&larr; " if i == 0 else ""}{esc(label)}</a>'
        for i, (label, href) in enumerate(back_links))
    parts.append(f'<p class="back">{back}</p>\n')
    parts.append(f'<h1>{t["h1"].format(**kw)}</h1>\n')
    parts.append(f'<p class="muted">{t["stand"].format(date=esc(date))}</p>\n')

    if not tables:
        # Rarely reached with real data (every swept area has changing
        # tables), but a page claiming "0 Orte, davon 0%" would be worse than
        # one saying so plainly.
        parts.append(f'<p>{t["empty"].format(**kw)}</p>\n')
    else:
        parts.append(f'<p>{t["intro"].format(**kw)}</p>\n')

    # {Name_for} is for the languages whose CTA starts with the name (German:
    # "Die Schweiz auf der Karte öffnen"); mid-sentence languages take
    # {name_for} and keep its article lowercase ("Ouvrir la Bretagne …").
    parts.append(_map_link(summary["bbox"], t["map_cta"].format(
        name=name, name_for=name_for,
        Name_for=name_for[0].upper() + name_for[1:])))

    parts.append(f'<h2>{t["numbers_h2"].format(**kw)}</h2>\n')
    parts.append(f'<table>\n<tr><th class="l">{esc(t["th_things"])}</th>'
                 f'<th>{esc(t["th_places"])}</th></tr>\n')
    for s in STATUS_ORDER:
        parts.append(f'<tr><td class="l"><span class="dot {STATUS_CLASS[s]}"></span>'
                     f'{esc(t["statuses"][s])}</td>'
                     f"<td>{fmt_num(summary[s], lang)}</td></tr>\n")
    parts.append(f'<tr><td class="l"><strong>{esc(t["total"])}</strong></td>'
                 f"<td><strong>{fmt_num(tables, lang)}</strong></td></tr>\n</table>\n")
    parts.append(f'<p class="muted">{t["toilets_note"].format(**kw)}</p>\n')

    # Help and navigation come BEFORE the named-places table: that table runs
    # to hundreds of rows in a big Land, and everything printed after it was
    # effectively unreachable (flagged 2026-08-23). The table is what you
    # scroll for; the sections a reader acts on must not hide below it.
    parts.append(f'<h2>{esc(t["help_h2"])}</h2>\n')
    parts.append(f'<p>{t["help"].format(**kw)}</p>\n')

    if page.get("siblings"):
        body = _nav_list(page["siblings"], lang, exclude_href=f"{slug}.html")
        if body:
            parts.append(f'<h2>{esc(t["siblings_h2"])}</h2>\n')
            parts.append(body)
    parts.append(_countries_section(page.get("countries"), lang,
                                    own_href=f"{slug}.html"))

    if summary["named"]:
        parts.append(f'<h2>{esc(t["named_h2"])}</h2>\n')
        parts.append(f'<p>{t["named_intro"].format(**kw)}</p>\n')
        parts.append('<div class="scroll">\n<table>\n')
        parts.append(f'<tr><th class="l">{esc(t["th_place"])}</th>'
                     f'<th class="l">{esc(t["th_kind"])}</th>'
                     f'<th>{esc(t["th_count"])}</th>'
                     f"{_status_head(t['statuses'])}</tr>\n")
        for g in summary["named"]:
            parts.append(
                f'<tr><td class="l">{esc(g["name"])}</td>'
                f'<td class="l">{esc(amenity_label(g["amenity"], lang))}</td>'
                f'<td>{fmt_num(g["count"], lang)}</td>'
                f'{_status_cells(g["statuses"], lang)}</tr>\n')
        parts.append("</table>\n</div>\n")

    parts.append(t["footer"].format(up=UP))
    parts.append("\n</body>\n</html>\n")
    return "".join(parts)


def render_land(summary: dict, summaries, generated_at: str,
                base_url: str = SITE_BASE_URL,
                base_path: str = PAGES_BASE_PATH, countries=None) -> str:
    """A German Bundesland page — render_area with the German forms filled in.
    German needs no inflection table here: "in {name}" is correct for all 16
    Länder (Switzerland, which needs "in der", lives in COUNTRY_PAGES)."""
    return render_area({
        "lang": "de",
        "summary": summary,
        "name_in": f"in {summary['name']}",
        "crumb_extra": [(L["de"]["crumb_hub"], f"{base_url}{base_path}")],
        "back": [(L["de"]["back_hub"], "./"), (L["de"]["back_map"], UP)],
        "siblings": [{"label": s["name"], "href": f"{s['slug']}.html",
                      "tables": s["tables"]} for s in summaries],
        "countries": countries,
    }, generated_at, base_url, base_path)


def render_index(summaries, generated_at: str, base_url: str = SITE_BASE_URL,
                 base_path: str = PAGES_BASE_PATH, countries=None) -> str:
    total = sum(s["tables"] for s in summaries)
    unknown = sum(s["unknown"] for s in summaries)
    date = de_date(generated_at)
    canonical = f"{base_url}{base_path}"
    desc = (f"Wickeltische in Deutschland nach Bundesland: {de_num(total)} Orte aus "
            f"OpenStreetMap, bei {de_num(unknown)} davon ist der Raum nicht erfasst.")

    parts = [_head("Wickeltische nach Bundesland — PapaMap", desc, canonical,
                   "de", base_url)]
    parts.append(f'<p class="back"><a href="{UP}">&larr; Zur Karte</a> · '
                 '<a href="rangliste.html">Rangliste</a></p>\n')
    parts.append("<h1>Wickeltische nach Bundesland</h1>\n")
    parts.append(f'<p class="muted">Stand {esc(date)} · Daten aus OpenStreetMap</p>\n')
    parts.append(
        f"<p>OpenStreetMap kennt in Deutschland <strong>{de_num(total)}</strong> Orte mit "
        f"Wickeltisch. Bei <strong>{de_num(unknown)}</strong> davon ist nicht erfasst, in "
        "welchem Raum der Tisch steht — ob ein Vater also überhaupt an ihn herankommt. "
        "Pro Bundesland aufgeschlüsselt:</p>\n")
    parts.append('<div class="scroll">\n<table>\n')
    parts.append(f'<tr><th class="l">Bundesland</th><th>Orte</th>{_status_head()}'
                 "<th>Toiletten</th></tr>\n")
    for s in summaries:
        parts.append(
            f'<tr><td class="l"><a href="{esc(s["slug"])}.html">{esc(s["name"])}</a></td>'
            f'<td>{de_num(s["tables"])}</td>'
            f"{_status_cells({k: s[k] for k in STATUS_ORDER})}"
            f'<td>{de_num(s["toilets_total"])}</td></tr>\n')
    parts.append("</table>\n</div>\n")
    parts.append(
        '<p class="muted">Alphabetisch, nicht nach Anzahl sortiert. Eine Rangliste wäre '
        "irreführend: die Zahlen messen, wie gründlich in einem Land gemappt wurde, nicht "
        "wie gut es mit Wickeltischen versorgt ist. Dieselbe Einschränkung wie beim "
        f'Städtevergleich in den <a href="{UP}methods.html">Methoden</a>. Was sich '
        "ehrlich vergleichen lässt, ist die Veränderung — die steht auf der "
        '<a href="rangliste.html">Rangliste</a>. Die '
        "Spalte <em>Toiletten</em> zählt alle erfassten öffentlichen Toiletten, mit oder "
        "ohne Wickeltisch.</p>\n")
    parts.append(_countries_section(countries, "de", own_href="./"))
    parts.append(FOOTER.format(up=UP))
    parts.append("\n</body>\n</html>\n")
    return "".join(parts)


def render_france_hub(region_summaries, generated_at: str,
                      base_url: str = SITE_BASE_URL,
                      base_path: str = PAGES_BASE_PATH, countries=None) -> str:
    """france.html — the hub the 13 région pages hang off, playing the role
    /wickeltische/ plays for the Bundesländer, in French."""
    t = L["fr"]
    total = sum(s["tables"] for s in region_summaries)
    unknown = sum(s["unknown"] for s in region_summaries)
    date = fmt_date(generated_at, "fr")
    canonical = f"{base_url}{base_path}france.html"
    nums = {"total": fmt_num(total, "fr"), "unknown": fmt_num(unknown, "fr")}

    parts = [_head(t["hub_title"], t["hub_desc"].format(**nums), canonical,
                   "fr", base_url)]
    parts.append(f'<p class="back"><a href="{UP}">&larr; {esc(t["back_map"])}</a> · '
                 f'<a href="{board_file("fr")}">{esc(BOARD_LABEL["fr"])}</a></p>\n')
    parts.append(f'<h1>{esc(t["hub_h1"])}</h1>\n')
    parts.append(f'<p class="muted">{t["stand"].format(date=esc(date))}</p>\n')
    parts.append(f'<p>{t["hub_intro"].format(**nums)}</p>\n')
    parts.append('<div class="scroll">\n<table>\n')
    parts.append(f'<tr><th class="l">{esc(t["hub_col"])}</th>'
                 f'<th>{esc(t["th_places"])}</th>{_status_head(t["statuses"])}'
                 f'<th>{esc(t["hub_toilets"])}</th></tr>\n')
    for s in region_summaries:
        parts.append(
            f'<tr><td class="l"><a href="{esc(s["slug"])}.html">{esc(s["name"])}</a></td>'
            f'<td>{fmt_num(s["tables"], "fr")}</td>'
            f"{_status_cells({k: s[k] for k in STATUS_ORDER}, 'fr')}"
            f'<td>{fmt_num(s["toilets_total"], "fr")}</td></tr>\n')
    parts.append("</table>\n</div>\n")
    parts.append(f'<p class="muted">{t["hub_note"]}</p>\n')
    parts.append(f'<h2>{esc(t["help_h2"])}</h2>\n')
    parts.append(f'<p>{t["help"].format(up=UP, methods=t["methods"])}</p>\n')
    parts.append(_countries_section(countries, "fr", own_href="france.html"))
    parts.append(t["footer"].format(up=UP))
    parts.append("\n</body>\n</html>\n")
    return "".join(parts)


def write_pages(summaries, out_dir: str, generated_at: str,
                base_url: str = SITE_BASE_URL,
                base_path: str = PAGES_BASE_PATH, countries=None) -> list:
    """Write the German index + one page per Land. Written one file at a time
    (atomically each), so a crash leaves the previous night's pages served
    rather than a half-written one."""
    written = []
    for s in summaries:
        path = str(Path(out_dir) / f"{s['slug']}.html")
        write_text_atomic(render_land(s, summaries, generated_at, base_url,
                                      base_path, countries=countries), path)
        written.append(path)
    path = str(Path(out_dir) / "index.html")
    write_text_atomic(render_index(summaries, generated_at, base_url,
                                   base_path, countries=countries), path)
    written.append(path)
    return written


def write_all_pages(areas, features, area_by_key, toilets_by_area,
                    out_dir: str, generated_at: str,
                    base_url: str = SITE_BASE_URL,
                    base_path: str = PAGES_BASE_PATH) -> list:
    """Everything /wickeltische/ holds except the leaderboard: the 16 German
    Land pages and their index, one page per other swept country in its own
    language, and the 13 région pages behind france.html.

    Gated per country on its sweep being complete in `areas`: a
    PAPAMAP_COUNTRIES=dk build writes danmark.html and nothing German, rather
    than publishing an index that claims Germany has one Bundesland (a partial
    German sweep can't reach here — run.py aborts unless every area
    succeeded). The shared country list only links pages this build wrote, so
    it can never link a 404."""
    by_area = group_by_area(features, area_by_key)
    swept = {n for n, _ in areas}

    german = all(n in swept for n in BUNDESLAENDER)
    land_summaries = [summarize(n, by_area.get(n, []),
                                toilets_by_area.get(n, 0))
                      for n in sorted(BUNDESLAENDER, key=sort_key)] if german else []

    country_entries = []
    for cc, (lang, name, name_in, name_for) in COUNTRY_PAGES.items():
        area_names = [a for a, _ in COUNTRY_AREAS[cc]]
        if not all(a in swept for a in area_names):
            continue
        feats = [f for a in area_names for f in by_area.get(a, [])]
        toilets = sum(toilets_by_area.get(a, 0) for a in area_names)
        country_entries.append({
            "cc": cc, "lang": lang, "name_in": name_in, "name_for": name_for,
            "summary": summarize(name, feats, toilets),
        })

    region_entries = []
    if any(e["cc"] == "fr" for e in country_entries):
        for r in FRANCE_REGIONS:
            name_in, name_for = FRANCE_REGION_FORMS[r]
            region_entries.append({
                "name_in": name_in, "name_for": name_for,
                "summary": summarize(r, by_area.get(r, []),
                                     toilets_by_area.get(r, 0)),
            })
        region_entries.sort(key=lambda e: sort_key(e["summary"]["name"]))

    countries_nav = [{"label": e["summary"]["name"],
                      "href": f"{e['summary']['slug']}.html",
                      "tables": e["summary"]["tables"]}
                     for e in country_entries]
    if german:
        countries_nav.append({"label": "Deutschland", "href": "./",
                              "tables": sum(s["tables"] for s in land_summaries)})
    countries_nav.sort(key=lambda it: sort_key(it["label"]))

    written = []
    if german:
        written += write_pages(land_summaries, out_dir, generated_at,
                               base_url, base_path, countries=countries_nav)

    region_siblings = [{"label": e["summary"]["name"],
                        "href": f"{e['summary']['slug']}.html",
                        "tables": e["summary"]["tables"]}
                       for e in region_entries]
    for e in country_entries:
        if e["cc"] == "fr":
            # France's page is the hub over the 13 régions, not an area page.
            html_text = render_france_hub(
                [x["summary"] for x in region_entries], generated_at,
                base_url, base_path, countries=countries_nav)
        else:
            html_text = render_area({
                "lang": e["lang"], "summary": e["summary"],
                "name_in": e["name_in"], "name_for": e["name_for"],
                "back": [(L[e["lang"]]["back_map"], UP)],
                "countries": countries_nav,
            }, generated_at, base_url, base_path)
        path = str(Path(out_dir) / f"{e['summary']['slug']}.html")
        write_text_atomic(html_text, path)
        written.append(path)

    for e in region_entries:
        html_text = render_area({
            "lang": "fr", "summary": e["summary"],
            "name_in": e["name_in"], "name_for": e["name_for"],
            "crumb_extra": [(L["fr"]["crumb_hub"],
                             f"{base_url}{base_path}france.html")],
            "back": [(L["fr"]["back_hub"], "france.html"),
                     (L["fr"]["back_map"], UP)],
            "siblings": region_siblings,
            "countries": countries_nav,
        }, generated_at, base_url, base_path)
        path = str(Path(out_dir) / f"{e['summary']['slug']}.html")
        write_text_atomic(html_text, path)
        written.append(path)

    return written
