from __future__ import annotations

import html
import json
import re
import unicodedata
from pathlib import Path

from .config import PAGES_BASE_PATH, SITE_BASE_URL
from .export import write_text_atomic

# One static page per Bundesland, regenerated by every full build.
#
# Why they exist: the map is a single URL for two countries, so search demand
# shaped like "Wickeltisch Bayern" has nothing to match — the place names live
# inside a 2.6 MB geojson that crawlers read as a download, not as text. These
# pages put the counts and the names into HTML.
#
# German only, and deliberately: the audience searching for a Wickeltisch in
# Hessen searches in German. That is also why they carry no hreflang alternates
# — same reasoning as impressum.html and datenschutz.html.
#
# Unlike index.html, these files are rewritten nightly, so hard-coded counts in
# the copy, the meta description and the JSON-LD are safe here — the "no counts
# in the markup" rule on the homepage is about hand-maintained files that rot.

GERMAN_MONTHS = ("Januar", "Februar", "März", "April", "Mai", "Juni", "Juli",
                 "August", "September", "Oktober", "November", "Dezember")

# ä→ae rather than ä→a: "baden-wuerttemberg" is the spelling German readers and
# German keyboards produce, and the slug is a public URL we have to keep stable.
_TRANSLIT = str.maketrans({
    "ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss",
    "Ä": "Ae", "Ö": "Oe", "Ü": "Ue",
})

# The amenity tag is a controlled OSM vocabulary, so a lookup table can cover
# it: these 20 values are 99% of the German dataset. Anything else falls back to
# the raw value with underscores stripped — a page that reads half-German is
# better than one that silently drops the type. `null` (a shop, most often a dm
# or Rossmann) has no amenity at all and renders as an em dash.
AMENITY_DE = {
    "toilets": "Öffentliche Toilette",
    "restaurant": "Restaurant",
    "cafe": "Café",
    "fast_food": "Imbiss",
    "community_centre": "Bürgerhaus",
    "library": "Bibliothek",
    "fuel": "Tankstelle",
    "pub": "Kneipe",
    "biergarten": "Biergarten",
    "ice_cream": "Eisdiele",
    "social_facility": "Soziale Einrichtung",
    "townhall": "Rathaus",
    "doctors": "Arztpraxis",
    "pharmacy": "Apotheke",
    "place_of_worship": "Kirche",
    "cinema": "Kino",
    "theatre": "Theater",
    "hospital": "Krankenhaus",
    "marketplace": "Marktplatz",
    "kindergarten": "Kindergarten",
}

# The pages sit one directory below the site root (PAGES_BASE_PATH), so this
# reaches the map, the methods page and the legal pages. Relative on purpose:
# only the canonical and the JSON-LD breadcrumb have to be absolute, and
# relative links mean a page renders and navigates correctly off a local
# `python3 -m http.server -d web` too.
UP = "../"

STATUS_ORDER = ("accessible", "female_only", "unknown")
STATUS_DE = {
    "accessible": "Erreichbar",
    "female_only": "Nur Damen-WC",
    "unknown": "Raum unbekannt",
}
STATUS_CLASS = {"accessible": "g", "female_only": "r", "unknown": "u"}


def slugify(name: str) -> str:
    """URL slug for a Bundesland. The 16 names are a fixed list, so this only
    has to be correct for them — but it is a function rather than a hand-written
    table so a name and its slug cannot drift apart (test_pages pins all 16)."""
    s = name.translate(_TRANSLIT).lower()
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-")


def sort_key(name: str) -> tuple:
    """Alphabetical order a German reader expects: Ärztehaus next to Apotheke,
    not stranded after Zoo where a raw codepoint sort puts it.

    ä sorts as a here, not as ae — that is DIN 5007-1, the ordering used for
    lists of names, and deliberately NOT the ae the slugs use (those follow the
    phone-book spelling because they are URLs someone might type). Decomposing
    and dropping the combining marks generalises it to the é and å that OSM
    names in a German Land do contain."""
    folded = unicodedata.normalize("NFKD", name.replace("ß", "ss").casefold())
    stripped = "".join(c for c in folded if not unicodedata.combining(c))
    return (stripped, name)


def de_num(n) -> str:
    """1234567 → '1.234.567'. The pages are German; the strip on the homepage
    already uses de-DE separators via toLocaleString."""
    return f"{int(n):,}".replace(",", ".")


def de_date(iso: str) -> str:
    """'2026-08-04T21:10:40+00:00' → '4. August 2026'. Hand-rolled because
    strftime('%B') follows the process locale, which on the server is C."""
    try:
        y, m, d = int(iso[0:4]), int(iso[5:7]), int(iso[8:10])
        return f"{d}. {GERMAN_MONTHS[m - 1]} {y}"
    except (ValueError, IndexError, TypeError):
        return ""


def amenity_label(amenity) -> str:
    if not amenity:
        return "—"
    return AMENITY_DE.get(amenity, str(amenity).replace("_", " "))


def group_by_area(features, area_by_key) -> dict:
    """Split the deduped feature list by the sweep area each object came from.

    `area_by_key` is {(osm_type, osm_id): area_name}, recorded while sweeping —
    the geojson itself carries no region field, and the Overpass area query is
    the only authority on which Land an object sits in. An object on a Länder
    boundary is returned by two sweeps and lands in the first one, matching how
    dedup_elements() keeps the first copy for the map."""
    out: dict[str, list] = {}
    for f in features:
        p = f["properties"]
        area = area_by_key.get((p["osm_type"], p["osm_id"]))
        if area is not None:
            out.setdefault(area, []).append(f)
    return out


def _bbox(features) -> list | None:
    """Feature bbox, padded, for the map deep link. Data-driven rather than a
    hard-coded Land box: the features come out of that Land's own area query, so
    their extent is inside it by construction and never needs maintaining. The
    minimum span keeps a Land with a single place from producing a zero-width
    box that fitBounds turns into a maximum-zoom view of one pin."""
    if not features:
        return None
    lons = [f["geometry"]["coordinates"][0] for f in features]
    lats = [f["geometry"]["coordinates"][1] for f in features]
    min_lon, max_lon, min_lat, max_lat = min(lons), max(lons), min(lats), max(lats)
    pad_lon = max((max_lon - min_lon) * 0.04, 0.05)
    pad_lat = max((max_lat - min_lat) * 0.04, 0.03)
    return [round(min_lon - pad_lon, 4), round(min_lat - pad_lat, 4),
            round(max_lon + pad_lon, 4), round(max_lat + pad_lat, 4)]


def summarize(name: str, features, toilets_total: int) -> dict:
    """Everything one Land page needs, computed from that Land's features.

    Named places are grouped by name: the dataset holds 181 shops called "dm"
    and 62 McDonald's, and 181 identical rows would read as generated filler
    rather than as data. The count carries the same information in one row."""
    status_counts = {s: 0 for s in STATUS_ORDER}
    groups: dict[str, dict] = {}
    unnamed = 0
    for f in features:
        p = f["properties"]
        status = p.get("status")
        if status in status_counts:
            status_counts[status] += 1
        place = (p.get("name") or "").strip()
        if not place:
            unnamed += 1
            continue
        g = groups.setdefault(place, {"name": place, "count": 0, "amenities": {},
                                      "statuses": {s: 0 for s in STATUS_ORDER}})
        g["count"] += 1
        if status in g["statuses"]:
            g["statuses"][status] += 1
        a = p.get("amenity")
        g["amenities"][a] = g["amenities"].get(a, 0) + 1
    named = []
    for g in sorted(groups.values(), key=lambda g: sort_key(g["name"])):
        # A chain can carry different amenity values across branches (café vs
        # fast_food); the most common one describes the group honestly enough,
        # and ties break on the value so the page is byte-stable between runs.
        top = sorted(g["amenities"].items(), key=lambda kv: (-kv[1], str(kv[0])))[0][0]
        named.append({"name": g["name"], "count": g["count"],
                      "amenity": top, "statuses": g["statuses"]})
    return {
        "name": name,
        "slug": slugify(name),
        "tables": len(features),
        "accessible": status_counts["accessible"],
        "female_only": status_counts["female_only"],
        "unknown": status_counts["unknown"],
        "toilets_total": toilets_total,
        "named": named,
        "named_places": len(features) - unnamed,
        "unnamed": unnamed,
        "bbox": _bbox(features),
    }


# ---- Rendering -------------------------------------------------------------
# Place names, amenity values and every other interpolated string originate in
# OpenStreetMap, which anyone can edit — so every one of them goes through
# esc(). The surrounding markup is a constant in this file.

def esc(s) -> str:
    return html.escape(str(s), quote=True)


def _jsonld(obj) -> str:
    """A <script> block's content is raw text, so HTML-escaping is exactly the
    wrong tool there (&quot; would land literally and break the JSON). json
    encodes it; escaping "</" is what stops any value from closing the tag."""
    body = json.dumps(obj, ensure_ascii=False).replace("</", "<\\/")
    return f'<script type="application/ld+json">{body}</script>\n\n'


# The same mark index.html carries, inlined for the same reason: a data URI
# costs no request and — unlike a root-relative /icon.svg — resolves from any
# directory depth, so the pages under wickeltische/ need no {up} dance. Without
# it a browser falls back to /favicon.ico, which this site does not serve: every
# generated page logged a 404 until 2026-08-17.
ICON = (
    '<link rel="icon" href="data:image/svg+xml,'
    "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E"
    "%3Ccircle cx='12' cy='12' r='11' fill='%23009e73'/%3E"
    "%3Crect x='5' y='12' width='14' height='2.6' rx='1.3' fill='%23fff'/%3E"
    "%3Ccircle cx='9' cy='9' r='2.2' fill='%23fff'/%3E"
    "%3Crect x='11.5' y='7.8' width='6.5' height='2.4' rx='1.2' fill='%23fff'/%3E"
    '%3C/svg%3E">'
)

STYLE = """\
  :root {
    --bg: #ffffff; --fg: #1c1c1c; --muted: #5a5a5a; --line: #d8d8d8;
    --green: #1a7f37; --red: #c0392b; --grey: #6e6e6e; --accent: #0b5fa5;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #1b1b1d; --fg: #e8e8e8; --muted: #a5a5a5; --line: #3a3a3d;
      --green: #4cc26b; --red: #e06553; --grey: #9a9a9a; --accent: #6ab0e8;
    }
  }
  body {
    margin: 0 auto; max-width: 46rem; padding: 1.5rem 1rem 4rem;
    background: var(--bg); color: var(--fg);
    font: 16px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif;
  }
  h1 { font-size: 1.6rem; margin: 0.5rem 0 0; }
  h2 { font-size: 1.2rem; margin-top: 2.2rem; border-bottom: 1px solid var(--line); padding-bottom: 0.3rem; }
  a { color: var(--accent); }
  .muted { color: var(--muted); font-size: 0.9rem; }
  .back { font-size: 0.9rem; }
  .dot { display: inline-block; width: 0.7em; height: 0.7em; border-radius: 50%;
         margin-right: 0.3em; vertical-align: baseline; }
  .g { background: var(--green); } .r { background: var(--red); } .u { background: var(--grey); }
  .cta { display: inline-block; margin: 0.6rem 0; padding: 0.55rem 0.9rem;
         border: 1px solid var(--accent); border-radius: 6px; text-decoration: none; }
  /* Long lists on a phone: let the table scroll sideways instead of the page. */
  .scroll { overflow-x: auto; }
  table { border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem; width: 100%; }
  th, td { border: 1px solid var(--line); padding: 0.3rem 0.55rem; text-align: right;
           white-space: nowrap; }
  th:first-child, td:first-child, th.l, td.l { text-align: left; white-space: normal; }
  th { font-weight: 600; }
  td.zero { color: var(--muted); }
  ul.laender { columns: 2; list-style: none; padding: 0; font-size: 0.95rem; }
  ul.laender li { margin: 0.25rem 0; break-inside: avoid; }
"""

FOOTER = """\
<h2>Daten &amp; Lizenz</h2>
<p class="muted">Alle Daten &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap
contributors</a>, unter der <a href="https://opendatacommons.org/licenses/odbl/">ODbL</a>. Diese
Seite wird jede Nacht aus einer Overpass-Abfrage neu erzeugt und speichert nichts über dich.
Wie gezählt und eingefärbt wird: <a href="{up}methods.html">Methoden</a> ·
<a href="{up}impressum.html">Impressum</a> ·
<a href="{up}datenschutz.html">Datenschutz</a></p>
<p class="muted">PapaMap ist kostenlos und werbefrei.
<a href="https://ko-fi.com/jakubwaller">&#9749; Kaffee spendieren</a>.</p>
"""


def _head(title: str, description: str, canonical: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="{esc(canonical)}">
{ICON}
<style>
{STYLE}</style>
</head>
<body>
"""


def _status_cells(counts) -> str:
    """The three status columns. A zero renders as a muted dash: in a 300-row
    table a column of "0"s is noise that hides the numbers that aren't zero."""
    out = []
    for s in STATUS_ORDER:
        n = counts.get(s, 0)
        out.append('<td class="zero">–</td>' if not n else f"<td>{de_num(n)}</td>")
    return "".join(out)


def _status_head() -> str:
    return "".join(
        f'<th><span class="dot {STATUS_CLASS[s]}"></span>{esc(STATUS_DE[s])}</th>'
        for s in STATUS_ORDER)


def _map_link(bbox, label: str) -> str:
    """Deep link into the map at this Land's extent. Without a bbox the map
    would open on the Germany+Denmark home view, which is no answer to
    "where in Hessen" — app.js reads the param and fits those bounds."""
    if not bbox:
        return ""
    q = ",".join(str(v) for v in bbox)
    return f'<p><a class="cta" href="{UP}?bbox={esc(q)}">{esc(label)} &rarr;</a></p>\n'


def _other_laender(summaries, current_slug: str) -> str:
    items = "".join(
        f'<li><a href="{esc(s["slug"])}.html">{esc(s["name"])}</a> '
        f'<span class="muted">{de_num(s["tables"])} Orte</span></li>'
        for s in summaries if s["slug"] != current_slug)
    return f'<ul class="laender">{items}</ul>\n' if items else ""


def render_land(summary: dict, summaries, generated_at: str,
                base_url: str = SITE_BASE_URL,
                base_path: str = PAGES_BASE_PATH) -> str:
    name, slug = summary["name"], summary["slug"]
    tables, unknown = summary["tables"], summary["unknown"]
    pct = round(100 * unknown / tables) if tables else 0
    date = de_date(generated_at)
    canonical = f"{base_url}{base_path}{slug}.html"
    title = f"Wickeltische in {name} — PapaMap"
    desc = (f"{de_num(tables)} Orte in {name} mit Wickeltisch, aus OpenStreetMap. "
            f"Bei {de_num(unknown)} davon ist nicht erfasst, in welchem Raum der "
            f"Tisch steht — und genau das lässt sich reparieren.")

    parts = [_head(title, desc, canonical)]
    # Breadcrumbs are the one bit of structured data that earns its place here:
    # they tell Google these are the leaves of one section, not 16 loose pages.
    parts.append(_jsonld({
        "@context": "https://schema.org", "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "PapaMap",
             "item": f"{base_url}/"},
            {"@type": "ListItem", "position": 2,
             "name": "Wickeltische nach Bundesland",
             "item": f"{base_url}{base_path}"},
            {"@type": "ListItem", "position": 3, "name": name, "item": canonical},
        ],
    }))
    parts.append('<p class="back"><a href="./">&larr; Alle Bundesländer</a> · '
                 f'<a href="{UP}">Zur Karte</a></p>\n')
    parts.append(f"<h1>Wickeltische in {esc(name)}</h1>\n")
    parts.append(f'<p class="muted">Stand {esc(date)} · Daten aus OpenStreetMap</p>\n')

    if not tables:
        # Never reached with real data (every Land has hundreds), but a page
        # claiming "0 Orte, davon 0%" would be worse than one saying so plainly.
        parts.append(f"<p>OpenStreetMap kennt in {esc(name)} derzeit keinen einzigen "
                     "Ort mit Wickeltisch. Das heißt fast sicher: es hat ihn noch "
                     "niemand erfasst.</p>\n")
    else:
        parts.append(
            f"<p>OpenStreetMap kennt in {esc(name)} <strong>{de_num(tables)}</strong> Orte "
            f"mit Wickeltisch. Bei <strong>{de_num(summary['accessible'])}</strong> ist "
            "erfasst, dass ein Vater ihn auch erreicht — Herren-WC, Unisex-WC oder "
            f"eigener Wickelraum. <strong>{de_num(summary['female_only'])}</strong> hängen "
            "nur im Damen-WC. Und bei "
            f"<strong>{de_num(unknown)}</strong> von {de_num(tables)} "
            f"({pct}&nbsp;%) hat schlicht niemand erfasst, in welchem Raum der Tisch "
            "steht. Das sind die grauen Pins auf der Karte, und die sind die "
            "eigentliche Aufgabe: die Frage beantwortet man vor Ort in unter einer "
            "Minute.</p>\n")

    parts.append(_map_link(summary["bbox"], f"{name} auf der Karte öffnen"))

    parts.append(f"<h2>Die Zahlen für {esc(name)}</h2>\n")
    parts.append('<table>\n<tr><th class="l">Wickeltische</th><th>Orte</th></tr>\n')
    for s in STATUS_ORDER:
        parts.append(f'<tr><td class="l"><span class="dot {STATUS_CLASS[s]}"></span>'
                     f'{esc(STATUS_DE[s])}</td><td>{de_num(summary[s])}</td></tr>\n')
    parts.append(f'<tr><td class="l"><strong>Gesamt</strong></td>'
                 f"<td><strong>{de_num(tables)}</strong></td></tr>\n</table>\n")
    parts.append(
        f'<p class="muted">In {esc(name)} sind außerdem '
        f"{de_num(summary['toilets_total'])} öffentliche Toiletten erfasst — die "
        "allermeisten ohne jede Angabe zum Wickeltisch. Ein Versorgungsvergleich "
        "zwischen Ländern lässt sich daraus nicht bauen; warum nicht, steht in den "
        f'<a href="{UP}methods.html">Methoden</a>.</p>\n')

    if summary["named"]:
        parts.append("<h2>Orte mit Namen</h2>\n")
        parts.append(
            f"<p>{de_num(summary['named_places'])} der {de_num(tables)} Orte tragen in "
            f"OpenStreetMap einen Namen, zusammen "
            f"{de_num(len(summary['named']))} verschiedene. Die übrigen "
            f"{de_num(summary['unnamed'])} sind fast durchweg öffentliche Toiletten ohne "
            "Namen — sie stehen auf der Karte, lassen sich hier aber nicht sinnvoll "
            "auflisten. Filialen einer Kette sind zu einer Zeile zusammengefasst.</p>\n")
        parts.append('<div class="scroll">\n<table>\n')
        parts.append(f'<tr><th class="l">Ort</th><th class="l">Art</th><th>Orte</th>'
                     f"{_status_head()}</tr>\n")
        for g in summary["named"]:
            parts.append(
                f'<tr><td class="l">{esc(g["name"])}</td>'
                f'<td class="l">{esc(amenity_label(g["amenity"]))}</td>'
                f'<td>{de_num(g["count"])}</td>{_status_cells(g["statuses"])}</tr>\n')
        parts.append("</table>\n</div>\n")

    parts.append("<h2>Wie du hier hilfst</h2>\n")
    parts.append(
        "<p>Ein grauer Pin heißt: den Wickeltisch gibt es, aber niemand hat erfasst, in "
        "welchem Raum er steht. Genau diese Antwort fehlt Vätern. Beantworten kann sie "
        "jeder mit einem kostenlosen OpenStreetMap-Konto, vor Ort, in unter einer "
        "Minute — der Link am Pin öffnet MapComplete direkt am richtigen Objekt. Die "
        "Antwort landet in OpenStreetMap, gehört allen und ist nach dem nächsten "
        f'nächtlichen Update hier zu sehen. <a href="{UP}methods.html#contribute">'
        "Schritt für Schritt</a>.</p>\n")

    parts.append("<h2>Andere Bundesländer</h2>\n")
    parts.append(_other_laender(summaries, slug))
    parts.append(FOOTER.format(up=UP))
    parts.append("\n</body>\n</html>\n")
    return "".join(parts)


def render_index(summaries, generated_at: str, base_url: str = SITE_BASE_URL,
                 base_path: str = PAGES_BASE_PATH) -> str:
    total = sum(s["tables"] for s in summaries)
    unknown = sum(s["unknown"] for s in summaries)
    date = de_date(generated_at)
    canonical = f"{base_url}{base_path}"
    desc = (f"Wickeltische in Deutschland nach Bundesland: {de_num(total)} Orte aus "
            f"OpenStreetMap, bei {de_num(unknown)} davon ist der Raum nicht erfasst.")

    parts = [_head("Wickeltische nach Bundesland — PapaMap", desc, canonical)]
    parts.append(f'<p class="back"><a href="{UP}">&larr; Zur Karte</a> · '
                 '<a href="rangliste.html">Rangliste</a></p>\n')
    parts.append("<h1>Wickeltische nach Bundesland</h1>\n")
    parts.append(f'<p class="muted">Stand {esc(date)} · Daten aus OpenStreetMap</p>\n')
    parts.append(
        f"<p>OpenStreetMap kennt in Deutschland <strong>{de_num(total)}</strong> Orte mit "
        f"Wickeltisch. Bei <strong>{de_num(unknown)}</strong> davon ist nicht erfasst, in "
        "welchem Raum der Tisch steht — ob ein Vater also überhaupt an ihn herankommt. "
        "Pro Bundesland aufgeschlüsselt:</p>\n")
    parts.append('<div class="scroll">\n<table>\n')
    parts.append(f'<tr><th class="l">Bundesland</th><th>Orte</th>{_status_head()}'
                 "<th>Toiletten</th></tr>\n")
    for s in summaries:
        parts.append(
            f'<tr><td class="l"><a href="{esc(s["slug"])}.html">{esc(s["name"])}</a></td>'
            f'<td>{de_num(s["tables"])}</td>'
            f"{_status_cells({k: s[k] for k in STATUS_ORDER})}"
            f'<td>{de_num(s["toilets_total"])}</td></tr>\n')
    parts.append("</table>\n</div>\n")
    parts.append(
        '<p class="muted">Alphabetisch, nicht nach Anzahl sortiert. Eine Rangliste wäre '
        "irreführend: die Zahlen messen, wie gründlich in einem Land gemappt wurde, nicht "
        "wie gut es mit Wickeltischen versorgt ist. Dieselbe Einschränkung wie beim "
        f'Städtevergleich in den <a href="{UP}methods.html">Methoden</a>. Was sich '
        "ehrlich vergleichen lässt, ist die Veränderung — die steht auf der "
        '<a href="rangliste.html">Rangliste</a>. Die '
        "Spalte <em>Toiletten</em> zählt alle erfassten öffentlichen Toiletten, mit oder "
        "ohne Wickeltisch.</p>\n")
    parts.append(FOOTER.format(up=UP))
    parts.append("\n</body>\n</html>\n")
    return "".join(parts)


def write_pages(summaries, out_dir: str, generated_at: str,
                base_url: str = SITE_BASE_URL,
                base_path: str = PAGES_BASE_PATH) -> list:
    """Write index + one page per Land. Written last in the build and one file
    at a time (atomically each), so a crash leaves the previous night's pages
    served rather than a half-written one."""
    written = []
    for s in summaries:
        path = str(Path(out_dir) / f"{s['slug']}.html")
        write_text_atomic(render_land(s, summaries, generated_at, base_url, base_path), path)
        written.append(path)
    path = str(Path(out_dir) / "index.html")
    write_text_atomic(render_index(summaries, generated_at, base_url, base_path), path)
    written.append(path)
    return written
